## NumPy是一个关于矩阵运算的库，这个库就是让python能够进行矩阵话的操作，而不用去写循环操作。

In [1]:
import numpy 

### 查看当前numpy的版本

In [2]:
numpy.__version__

'1.14.3'

### 一般将numpy重新命名为np

In [3]:
import numpy as np

In [4]:
np.full((3,5),666)#创建矩阵

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### numpy包含两种基本的数据类型：数组和矩阵。

In [5]:
a1=numpy.array([1,2,3]) #定义一个数组
a2=np.array([2,3,4])
a1+a2 #对于元素相加

array([3, 5, 7])

In [6]:
a1*2                 #乘一个数

array([2, 4, 6])

In [7]:
a2**3              #表示对数组中的每个数做平方

array([ 8, 27, 64], dtype=int32)

In [8]:
a1[1]               #取值，注意的是它是以0为开始坐标，不matlab不同

2

In [9]:
a3=np.array([[1,2,3],[4,5,6]])  #定义多维数组
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a3[0]             #取出第一行的数据

array([1, 2, 3])

In [11]:
a3[0,0]           #第一行第一个数据

1

In [12]:
a3[0][0]          #也可用这种方式

1

In [13]:
##数组乘，对应元素相乘
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a1*a2

array([ 4, 10, 18])

### Numpy有许多的创建数组的函数：

In [14]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)             # Prints "[[ 0.  0.]
                     #          [ 0.  0.]]"
print()
b = np.ones((1,2))   # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"
print()
c = np.full((2,2), 7) # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                      #          [ 7.  7.]]"
print()
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)             # Prints "[[ 1.  0.]
print()                    #          [ 0.  1.]]"

e = np.random.random((2,2)) # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
print()                            #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]

[[1. 1.]]

[[7 7]
 [7 7]]

[[1. 0.]
 [0. 1.]]

[[0.42984896 0.44791531]
 [0.13121258 0.6914554 ]]



### 数组索引(Array indexing)

### 矩阵

#### 矩阵的操作与Matlab语言有很多的相关性。

In [15]:
#创建矩阵
m=np.mat([1,2,3])#将Python的列表转换成NumPy的矩阵
m

matrix([[1, 2, 3]])

In [16]:
#取值
m[0,:]                #取一行

matrix([[1, 2, 3]])

In [17]:
m[0,1]              #第一行，第2个数据

2

In [18]:
#m[0][1]             #注意不能像数组那样取值了

In [19]:
#将Python的列表转换成NumPy的矩阵
list=[1,2,3]
np.mat(list)

matrix([[1, 2, 3]])

In [20]:
#矩阵相乘
m1=np.mat([1,2,3])     #1行3列
m2=np.mat([4,5,6]) 
m1*m2.T             #注意左列与右行相等 m2.T为转置操作

matrix([[32]])

In [21]:
np.multiply(m1,m2)     #执行点乘操作，要使用函数，特别注意

matrix([[ 4, 10, 18]])

In [22]:
#排序
m=np.mat([[2,5,1],[4,6,2]])    #创建2行3列矩阵
print(m)
m.sort()                    #对每一行进行排序
m

[[2 5 1]
 [4 6 2]]


matrix([[1, 2, 5],
        [2, 4, 6]])

In [23]:
m.shape                     #获得矩阵的行列数


(2, 3)

In [24]:
m.shape[0]                  #获得矩阵的行数

2

In [25]:
m.shape[1]                  #获得矩阵的列数

3

In [26]:
#索引取值
m[0,:]                      #取得第一行的所有元素

matrix([[1, 2, 5]])

In [27]:
m[1,0:1]                    #第二行第一个元素，注意左闭右开

matrix([[2]])

In [28]:
m[1,0:3]

matrix([[2, 4, 6]])

In [29]:
m[1,0:2]

matrix([[2, 4]])

### 扩展矩阵函数tile()

In [30]:
x=np.mat([0,0,0])
print(x)
print()
np.tile(x,(3,1))           #即将x扩展3个，j=1,表示其列数不变

[[0 0 0]]



matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [31]:
np.tile(x,(2,2))           #x扩展2次，j=2,横向扩展

matrix([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])