## python中的list和array的不同之处 及转换

### list是列表,可以通过索引查找数值，但是不能对整个列表进行数值运算

In [1]:
b=[1,2]

In [2]:
b[1]

2

In [3]:
type(b)

list

In [4]:
b+b

[1, 2, 1, 2]

### array是数组，也可以通过索引值查找数据，但是能对整个数组进行数值运算

In [6]:
import numpy as np

In [7]:
a=np.array([1,2])

In [8]:
a[1]

2

In [9]:
type(a)

numpy.ndarray

In [10]:
a+a

array([2, 4])

### 转换

In [12]:
u = np.array([[1,2],[3,4]]) 

In [13]:
m = u.tolist() #转换为list 

In [14]:
type(m)

list

In [15]:
m.remove(m[0]) #移除m[0] 

In [16]:
m

[[3, 4]]

In [18]:
u[0][1]

2

In [19]:
m = np.array(m) #转换为array

In [20]:
type(m)

numpy.ndarray

## Python之数组(array)使用方法总结与Numpy中的数组用法

In [21]:
import numpy as np
from array import * 

In [26]:
myarray=np.array([1])#表示创建一个interger类型的数组 

## Numpy：

### NumPy数组是一个多维数组对象，称为ndarray。其由两部分组成：

### 实际的数据
### 描述这些数据的元数据
### 大部分操作仅针对于元数据，而不改变底层实际的数据。

### 关于NumPy数组有几点必需了解的：

#### NumPy数组的下标从0开始。
#### 同一个NumPy数组中所有元素的类型必须是相同的。

#### 在详细介绍NumPy数组之前。先详细介绍下NumPy数组的基本属性。NumPy数组的维数称为秩（rank），一维数组的秩为1，二维数组的秩为2，以此类推。在NumPy中，每一个线性的数组称为是一个轴（axes），秩其实是描述轴的数量。比如说，二维数组相当于是两个一维数组，其中第一个一维数组中每个元素又是一个一维数组。所以一维数组就是NumPy中的轴（axes），第一个轴相当于是底层数组，第二个轴是底层数组里的数组。而轴的数量——秩，就是数组的维数。

#### NumPy的数组中比较重要ndarray对象属性有：

#### ndarray.ndim：数组的维数（即数组轴的个数），等于秩。最常见的为二维数组（矩阵）。

#### ndarray.shape：数组的维度。为一个表示数组在每个维度上大小的整数元组。例如二维数组中，表示数组的“行数”和“列数”。ndarray.shape返回一个元组，这个元组的长度就是维度的数目，即ndim属性。

#### ndarray.size：数组元素的总个数，等于shape属性中元组元素的乘积。

#### ndarray.dtype：表示数组中元素类型的对象，可使用标准的Python类型创建或指定dtype。另外也可使用前一篇文章中介绍的NumPy提供的数据类型。

#### ndarray.itemsize：数组中每个元素的字节大小。例如，一个元素类型为float64的数组itemsiz属性值为8(float64占用64个bits，每个字节长度为8，所以64/8，占用8个字节），又如，一个元素类型为complex32的数组item属性为4（32/8）。

#### ndarray.data：包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。

In [28]:
import numpy as np
from numpy import * 

In [29]:
a=np.array([[1,2],[2,3]])
a.ndim#数组的维数 

2

In [30]:
a.shape#数组的维度，即行数和列数 

(2, 2)

In [31]:
a.dtype#数组中元素的类型 

dtype('int32')

In [32]:
a.size#数组元素的总个数 

4

#### 注意：使用array函数创建时，参数必须是由方括号括起来的列表，而不能使用多个数值作为参数调用array。

In [33]:
#a = array(1,2,3,4)    # 错误  
a = array([1,2,3,4])  # 正确  

#### 可以在创建时显式指定数组中元素的类型： 

In [35]:
c = array( [ [1,2], [3,4] ], dtype=complex)  
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

#### NumPy提供一个类似arange的函数返回一个数列形式的数组: 

In [36]:
arange(4) 

array([0, 1, 2, 3])

In [37]:
arange(10,30,5)#10-30步长为5 

array([10, 15, 20, 25])

#### 当arange使用浮点数参数时，由于浮点数精度有限，通常无法预测获得的元素个数。因此，最好使用函数linspace去接收我们想要的元素个数来代替用range来指定步长。 

In [38]:
np.linspace(10,30,5)#这里5表示的是要输出5个数 

array([10., 15., 20., 25., 30.])